substitutions:
  devicename: water-softener
  fullname: Water Softener

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home
  # fast_connect: true

# Enable logging
logger:
  level: info

api:
  password: !secret api_password

ota:
  password: !secret ota_password

# mqtt:
#   broker: 192.168.100.5
#   topic_prefix: esphome/${devicename}

time:
  - platform: sntp

switch:
  - platform: restart
    name: ${fullname} Restart

sensor:
  - platform: uptime
    name: ${fullname} Uptime

  - platform: ultrasonic
    trigger_pin: D2
    echo_pin: D1
    name: Saltlevel 1 Percent
    update_interval: 1h
    # expire_after: 4000s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    # retain: true
    filters:
      - lambda: return (int)((1 - (x / 0.35)) * 100.0);

  - platform: ultrasonic
    trigger_pin: D5
    echo_pin: D0
    name: Saltlevel 2 Percent
    update_interval: 1h
    # expire_after: 4000s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    # retain: true
    filters:
      - lambda: return (int)((1 - (x / 0.35)) * 100.0);
